### ISSUE TITLE
Error while running waternet - no module named config

### ISSUE THREAD

**Issue by sagarr** [treigerm/WaterNet#2]
Hi @treigerm, 

whenever I'm running waternet in docker, I'm getting below error:
```
Traceback (most recent call last):
  File "waterNet.py", line 7, in <module>
    from waterNet.config import DATASETS, OUTPUT_DIR, TRAIN_DATA_DIR, LABELS_DIR
  File "/home/rohankar/Projects/tomtom/concept-dev/WaterNet/waterNet.py", line 7, in <module>
    from waterNet.config import DATASETS, OUTPUT_DIR, TRAIN_DATA_DIR, LABELS_DIR
ImportError: No module named config
```

Can you help?

**Comment by treigerm** [comment]
I think the problem was that I forgot the __init__.py file in the `waterNet` module. Now that I've uploaded one can you try it again and see if it works?

**Comment by sagarr** [comment]
It worked! thanks for help, I'm python and ML noob. :)
